server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Dossiers statiques, servis tels quels
    location /assets/ {
        try_files $uri =404;
    }

    location /fonts/ {
        try_files $uri =404;
    }

    location /fontawesome/ {
        try_files $uri =404;
    }

    location /media/ {
        try_files $uri =404;
    }

    location /mock/ {
        try_files $uri =404;
    }

    # Catch-all pour Angular router
    location / {
        try_files $uri $uri/ /index.html;
    }
}
